config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  get '/guest/', to: 'sessions#guest', as: 'guest'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:show]
    resources :foodtrucks, only: [:create, :index, :show]
    resources :donations, only: [:create, :index, :show]
    resources :perks, only: [:create, :index, :show]
    resources :categories, only: [:create, :index, :show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  TYPES = [
    "Hispanic",
    "Asian",
    "American",
    "Indian",
    "European"
  ]

  validates :name, presence: true
  validates :name, inclusion: { in: TYPES }

  has_many :foodtrucks
  has_many :donations, through: :foodtrucks, source: :donations
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates :amount, :foodtruck_id, :backer_id, presence: true
  validates :amount, numericality: { greater_than: 0 }
  belongs_to(:user, foreign_key: :backer_id)
  belongs_to :foodtruck
  belongs_to :perk


end

app/models/foodtruck.rb
# == Schema Information
#
# Table name: foodtrucks
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  author_id    :string           not null
#  integer      :string           not null
#  end_date     :date             not null
#  image        :string           default("http://images.clipartpanda.com/food-delivery-truck-clipart-yTo8MzjTE.jpeg")
#  category_id  :integer          not null
#  funding_goal :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Foodtruck < ActiveRecord::Base
  validates :title, :description, :author_id, :end_date, :category_id, :funding_goal, presence: true
  validates :funding_goal, numericality: true

  belongs_to :category
  belongs_to(:user, foreign_key: :author_id)
  has_many :donations
  has_many :perks

end

app/models/perk.rb
class Perk < ActiveRecord::Base
  validates :name, :description, :amount, :foodtruck_id, presence: true
  validates :amount, numericality: true
  
  has_one :donation
  belongs_to :foodtruck
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many(:foodtrucks, foreign_key: :author_id)
  has_many(:donations, foreign_key: :backer_id)


  validates :password, length: {minimum: 6, allow_nil: true}
  validates :password_digest, :username, :session_token, presence: true
  attr_reader :password
  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.valid_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end


end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController

  def index
    @category = Category.includes(:foodtrucks).includes(foodtrucks: :user).includes(foodtrucks: :perks).includes(foodtrucks: :donations).all
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end
end

app/controllers/api/donations_controller.rb
class Api::DonationsController < ApplicationController
  
  def create
    @donation = current_user.donations.new(donation_params)
    if @donation.save
      render :show
    else
      render json: @donation.errors.full_messages, status: 422
    end
  end

  def show
    @donation = Donation.includes(:foodtruck).includes(:perks).find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(
      :amount, :foodtruck_id, :perk_id
    )
  end
end

app/controllers/api/foodtrucks_controller.rb
class Api::FoodtrucksController < ApplicationController
  def create
    @foodtruck = current_user.foodtrucks.new(foodtruck_params)
    @foodtruck.category_id = Category.find_by_name(params[:foodtruck][:category]).id

    if @foodtruck.save
      render :show
    else
      render json: @foodtruck.errors.full_messages, status: 422
    end
  end

  def index
    @foodtruck = Foodtruck.includes(:donations).includes(:perks).includes(:category).includes(:user).all
  end

  def show
    @foodtruck = Foodtruck.includes(:donations).includes(:perks).includes(:category).includes(:user).find(params[:id])
  end

  private

  def foodtruck_params
    params.require(:foodtruck).permit(
      :title, :description, :end_date, :funding_goal, :image
    )
  end
end

app/controllers/api/perks_controller.rb
class Api::PerksController < ApplicationController
  def create
    @perk = Perk.new(perk_params)

    if @perk.save
      render :show
    else
      render json: @perk.errors.full_messages, status: 422
    end
  end

  def index
    @perks = Perk.includes(:foodtruck).includes(:donation).all
  end

  def show
    @perk = Perk.find(params[:id])
  end

  private

  def perk_params
    params.require(:perk).permit(
      :name, :description, :amount, :foodtruck_id
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])

  end

  def logout
    current_user.reset_session_token
    current_user.session_token = nil
  end

  def ensure_logged_in
    redirect_to new_session_url unless current_user
  end

  def ensure_not_logged_in
    redirect_to root_url if current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_not_logged_in, only: [:create, :new]
  before_action :ensure_logged_in, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Incorrect Password/Username"]
      render :new
    end
  end

  def destroy
    logout
    render json: {}
  end

  def guest
    @user = User.find_by_credentials(
      "Guest",
      "password"
    )
    login(@user)
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_not_logged_in, only: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/foodtrucks_helper.rb
module FoodtrucksHelper
end

app/helpers/perks_helper.rb
module PerksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodTruckStarter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
  <% if current_user %>
  <script>
    window.CURRENT_USER_ID = <%= current_user.id %>;
    window.CURRENT_USER_USERNAME = "<%= current_user.username %>";
  </script>
  <% end %>
</head>
<body>



  <!-- <div id="navbar">navbar here</div> -->

<!-- <% if current_user %>
<%= current_user.username %>
<%= button_to("Sign Out", session_url, method: :delete) %>
<% end %> -->

<%= yield %>

<!-- <%= flash[:errors] %> -->

</body>
</html>

app/views/users/new.html.erb
<!-- <h1> Sign Up </h1>

<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="Username">Username</label>
  <input type="text" name="user[username]" id="Username" value="">

  <label for="Password">Password</label>
  <input type="password" name="user[password]" id="Password" value="">

  <input type="submit" value="Sign Up">


</form> -->

<img src="http://www.uwishunu.com/wp-content/uploads/2015/04/night-market-philadelphia-food-truck1-1200vp.jpg")" id="sign-log-in-background" alt="">




<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div>
<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">


    <div class="row">
        <div class="col-md-offset-5 col-md-3">
            <div class="form-login">
            <h4 class="sign-log-title">Sign Up</h4>
            <label for="Username" class="sign-log-creds">Username</label>
            <input type="text" id="userName" name="user[username]" class="form-control input-sm chat-input" placeholder="Get Recognized" value="" />
            </br>
            <label for="Password" class="sign-log-creds">Password</label>
            <input type="password" name="user[password]" id="Password" value="" id="userPassword" class="form-control input-sm chat-input" placeholder="Secret Recipe To Success" />
            </br>
            <div class="wrapper">
            <span class="group-btn">
                <input type="submit" class="btn btn-success btn-md sign-log-guest-button" className="sign-in-submit-button">
                <%= link_to 'or Log In as Guest', guest_path %>
            </span>
            <ul>
              <%  if flash[:errors] %>
              <li class="errors">-<%= flash[:errors][0] %><li>
              <li class="errors">-<%= flash[:errors][1] %><li>
                <% end %>
            </ul>

            </div>
            </div>

        </div>
    </div>

</form>

</div>